# Generated by Django 5.1 on 2026-02-13

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0134_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rack_Inverter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tags", taggit.managers.TaggableManager(blank=True, through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name_plural": "Rack_Inverters",
                "ordering": ("name",),
            },
        ),
    ]
