# Generated by Django 5.1 on 2026-02-13

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0134_owner"),
    ]

    # This plugin does not define any custom models. Keep the initial migration
    # as a no-op for compatibility with existing installations.
    operations = []
