# Generated by Django 5.1 on 2026-02-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_rack_inverter", "0001_initial"),
    ]

    # Keep this migration as a no-op for upgrade path stability.
    operations = []
