# Generated by Django 5.1 on 2026-02-14

from django.db import migrations


def cleanup_legacy_scaffold(apps, schema_editor):
    legacy_table = "netbox_rack_inverter_rack_inverter"
    quote_name = schema_editor.quote_name
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)

    if legacy_table not in table_names:
        return

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT COUNT(*) FROM {quote_name(legacy_table)}")
        row_count = cursor.fetchone()[0]

    # Do not drop non-empty legacy tables to avoid destructive behavior.
    if row_count > 0:
        return

    with connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE {quote_name(legacy_table)}")

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    stale_content_types = ContentType.objects.filter(
        app_label="netbox_rack_inverter",
        model="rack_inverter",
    )
    Permission.objects.filter(content_type__in=stale_content_types).delete()
    stale_content_types.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_rack_inverter", "0002_delete_rack_inverter"),
    ]

    operations = [
        migrations.RunPython(cleanup_legacy_scaffold, migrations.RunPython.noop),
    ]
